### ISSUE TITLE
EmailAuth cannot handle actions after successful login

### ISSUE THREAD

**Issue by jokimina** [supabase-community/auth-ui#232]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

https://github.com/supabase/auth-ui/blob/main/packages/react/src/components/Auth/interfaces/EmailAuth.tsx#L78-L83

## To Reproduce

1. login with email and password
2. The login was successful, and the user information was returned, but the action could not continue

## Expected behavior

Can handle the action after login

## Screenshots
![1](https://github.com/supabase/auth-ui/assets/11460661/a6adbd52-fdbd-43f8-8f00-1c27e5c5d627)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Hallidayo** [comment]
Hi @jokimina, Are you using a framework with auth-ui?

**Comment by makkus183** [comment]
I can confirm this. I am using next.js as framework. 
When using email/pw login no redirect  to the given `redirectTo` happens after clicking the Sign In Button. The Login is successful btw, after reloading the page i am logged in.

**Comment by yepelinux** [comment]
any workarround?
