### ISSUE TITLE
Bug: Sign-in Error after patch

### ISSUE THREAD

**Issue by vishal-sarg** [supabase-community/auth-ui#31]
I was on "^0.1.7", it auto-upgraded to "^0.1.8"

which broke my sign-in

I am on supabase v1 which was working with 0.1.7, but after this patch this error is showing

For now, I've reverted to "0.1.7"

<img width="1440" alt="Screen Shot 2022-09-05 at 11 56 20 AM" src="https://user-images.githubusercontent.com/88632854/188374319-3f1eb9b7-c628-4f46-a9fd-de90d22b2f33.png">

**Comment by thorwebdev** [comment]
Yes, sorry, https://github.com/supabase-community/auth-ui/releases/tag/%40supabase%2Fauth-ui-react%400.1.8 updates to use supabase-js@rc version: https://supabase.com/docs/guides/auth/auth-helpers/auth-ui#set-up-auth-ui
