### ISSUE TITLE
Is there any sample code

### ISSUE THREAD

**Issue by LRboyz** [supabase-community/auth-ui#32]
I want to try to change the component. I want to listen to the listening events of his button clicks, but in fact I haven't found the corresponding API. Do you have sample code
![test](https://user-images.githubusercontent.com/48092353/191675804-efdb1c8a-1f96-40fa-aa7e-f2d776dc4a23.jpg)

**Comment by thorwebdev** [comment]
The documentation can be found here: https://supabase.com/docs/guides/auth/auth-helpers/auth-ui

I don't think there is a way to listen to button clicks currently. Can you outline why you want that?
