### ISSUE TITLE
TypeError: supabaseClient.auth.signInWithPassword is not a function

### ISSUE THREAD

**Issue by marcello-palmitessa** [supabase-community/auth-ui#35]
# Bug report

## Describe the bug
Using the Auth component **with only email authentication**, I get the error when the login form is submitted:
`
Unhandled Runtime Error
TypeError: supabaseClient.auth.signInWithPassword is not a function

Call Stack
eval
node_modules/@supabase/auth-ui-react/dist/esm/src/components/Auth/interfaces/EmailAuth.js (61:10)
` 

## To Reproduce
My code is:
`
      <Auth
        supabaseClient={supabaseClient}
        providers={[]}
      />
`

## Expected behavior

I expect 

## System information

- OS: macOS
- Browser: all (chrome, safari, firefox)
- Version of supabase-js:
    "@supabase/auth-helpers-nextjs": "^0.2.8",
    "@supabase/auth-helpers-react": "^0.2.4",
    "@supabase/auth-ui-react": "^0.2.0",
    "@supabase/supabase-js": "^1.35.7",

- Version of Node.js: 18.2.0

**Comment by MildTomato** [comment]
@marcello-palmitessa this seems like supabase-js is not installed.

Have you got the latest supabase-js@rc installed ?

`npm install @supabase/supabase-js@rc @supabase/auth-ui-react`

**Comment by marcello-palmitessa** [comment]
I missed that the auth-ui package reference the new 2.x RC version of supabase-js... I was using the latest stable 1.3.7... that's it.

Thanks to point me there, @MildTomato
