### ISSUE TITLE
Missing social login buttons in Auth component

### ISSUE THREAD

**Issue by Lucasvo1** [supabase-community/auth-ui#52]
# Bug report

## Describe the bug

<img width="389" alt="image" src="https://user-images.githubusercontent.com/109728866/198603269-eb99f75a-b8a1-4b1a-bb86-d820cf3ec4d4.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/109728866/198603803-5a7c90cd-64e2-4efa-815b-c16ea95efa10.png">

     <Auth
       supabaseClient={supabase}
        appearance={{ theme: ThemeSupa, 
        variables: {
        default: {
             colors: {
                 brand: 'red',
                 brandAccent: 'darkred',
                        },
               },
       }}
      theme="default"
      />
I added the Azure login in the settings and the option does not appear on the login screen.

**Comment by silentworks** [comment]
I think you might have misunderstood how the library works. It won't show the social auth button based on your settings inside of the Supabase Dashboard. You will need to enable this in the component itself in your code. You can do this by passing the `providers` property to the `Auth` component.

```ts
<Auth
   supabaseClient={supabase}
   providers={['azure']}
   appearance={{ theme: ThemeSupa, 
   variables: {
     default: {
       colors: {
         brand: 'red',
         brandAccent: 'darkred',
       },
     },
   }}
   theme="default",
/>
```

**Comment by Lucasvo1** [comment]
Perfect, thanks a lot!
